services:
  app:
    build: .
    container_name: icecream_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      # Configuracion para MySQL (Azure Flexible Server)
      SPRING_DATA_MYSQL_URI: jdbc:mysql://icecream7mysql.mysql.database.azure.com:3306/db_icecream?useSSL=true&requireSSL=false
      MYSQL_USER: dilan
      MYSQL_PASSWORD: Admin#0717

      # Configuracion para MongoDB (Atlas)
      SPRING_DATA_MONGODB_URI: mongodb+srv://dilan:mQ9Cs3o8WurKkY96@cluster0.8xrtd6b.mongodb.net/heladeria_db?retryWrites=true&w=majority
