spring.application.name=IceCream-SpringBoot
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Bases de datos en la nube
# Configuración de MySQL (Azure Flexible Server)
spring.datasource.url=${SPRING_DATA_MYSQL_URI}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

# Configuración de MongoDB (Atlas)
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}